# Generated by Django 2.2 on 2020-05-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('order_approval_number', models.IntegerField()),
                ('established_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('purchase_doc_seller', models.CharField(max_length=50)),
                ('purchase_doc_number', models.IntegerField()),
                ('purchase_doc_serial', models.CharField(max_length=50)),
                ('purchase_doc_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('measurement', models.CharField(choices=[('VNT', 'vnt.'), ('KOMPL', 'kompl.')], default='VNT', max_length=10)),
                ('amount', models.IntegerField()),
                ('sum', models.FloatField()),
                ('cost', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Form')),
            ],
        ),
    ]
